/*
 * This file is generated by jOOQ.
 */
package dev.laksitha.autogen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TerminalSettings implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String value;

    public TerminalSettings() {}

    public TerminalSettings(TerminalSettings value) {
        this.id = value.id;
        this.name = value.name;
        this.value = value.value;
    }

    public TerminalSettings(
        String id,
        String name,
        String value
    ) {
        this.id = id;
        this.name = name;
        this.value = value;
    }

    /**
     * Getter for <code>public.terminal_settings.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.terminal_settings.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.terminal_settings.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.terminal_settings.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.terminal_settings.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>public.terminal_settings.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TerminalSettings other = (TerminalSettings) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TerminalSettings (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
