/*
 * This file is generated by jOOQ.
 */
package dev.laksitha.autogen.tables;


import dev.laksitha.autogen.Keys;
import dev.laksitha.autogen.Public;
import dev.laksitha.autogen.tables.records.TerminalSettingsRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TerminalSettings extends TableImpl<TerminalSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.terminal_settings</code>
     */
    public static final TerminalSettings TERMINAL_SETTINGS = new TerminalSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TerminalSettingsRecord> getRecordType() {
        return TerminalSettingsRecord.class;
    }

    /**
     * The column <code>public.terminal_settings.id</code>.
     */
    public final TableField<TerminalSettingsRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.terminal_settings.name</code>.
     */
    public final TableField<TerminalSettingsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.terminal_settings.value</code>.
     */
    public final TableField<TerminalSettingsRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(256), this, "");

    private TerminalSettings(Name alias, Table<TerminalSettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TerminalSettings(Name alias, Table<TerminalSettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.terminal_settings</code> table reference
     */
    public TerminalSettings(String alias) {
        this(DSL.name(alias), TERMINAL_SETTINGS);
    }

    /**
     * Create an aliased <code>public.terminal_settings</code> table reference
     */
    public TerminalSettings(Name alias) {
        this(alias, TERMINAL_SETTINGS);
    }

    /**
     * Create a <code>public.terminal_settings</code> table reference
     */
    public TerminalSettings() {
        this(DSL.name("terminal_settings"), null);
    }

    public <O extends Record> TerminalSettings(Table<O> child, ForeignKey<O, TerminalSettingsRecord> key) {
        super(child, key, TERMINAL_SETTINGS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TerminalSettingsRecord> getPrimaryKey() {
        return Keys.TERMINAL_SETTINGS_PKEY;
    }

    @Override
    public TerminalSettings as(String alias) {
        return new TerminalSettings(DSL.name(alias), this);
    }

    @Override
    public TerminalSettings as(Name alias) {
        return new TerminalSettings(alias, this);
    }

    @Override
    public TerminalSettings as(Table<?> alias) {
        return new TerminalSettings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TerminalSettings rename(String name) {
        return new TerminalSettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TerminalSettings rename(Name name) {
        return new TerminalSettings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TerminalSettings rename(Table<?> name) {
        return new TerminalSettings(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
