/*
 * This file is generated by jOOQ.
 */
package dev.laksitha.autogen;


import dev.laksitha.autogen.tables.Terminal;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TERMINAL_NAME = Internal.createIndex(DSL.name("idx_terminal_name"), Terminal.TERMINAL, new OrderField[] { Terminal.TERMINAL.NAME }, false);
}
