/*
 * This file is generated by jOOQ.
 */
package dev.laksitha.autogen;


import dev.laksitha.autogen.tables.Terminal;
import dev.laksitha.autogen.tables.TerminalSettings;
import dev.laksitha.autogen.tables.records.TerminalRecord;
import dev.laksitha.autogen.tables.records.TerminalSettingsRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TerminalRecord> TERMINAL_PKEY = Internal.createUniqueKey(Terminal.TERMINAL, DSL.name("terminal_pkey"), new TableField[]{Terminal.TERMINAL.ID}, true);
    public static final UniqueKey<TerminalSettingsRecord> TERMINAL_SETTINGS_PKEY = Internal.createUniqueKey(TerminalSettings.TERMINAL_SETTINGS, DSL.name("terminal_settings_pkey"), new TableField[]{TerminalSettings.TERMINAL_SETTINGS.ID}, true);
}
