/*
 * This file is generated by jOOQ.
 */
package dev.laksitha.autogen;


import dev.laksitha.autogen.tables.Terminal;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.terminal</code>.
     */
    public static final Terminal TERMINAL = Terminal.TERMINAL;
}
