/*
 * This file is generated by jOOQ.
 */
package dev.laksitha.autogen;


import dev.laksitha.autogen.tables.Databasechangelog;
import dev.laksitha.autogen.tables.Databasechangeloglock;
import dev.laksitha.autogen.tables.Terminal;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.terminal</code>.
     */
    public static final Terminal TERMINAL = Terminal.TERMINAL;
}
