name: coupledchanges
description: "Check for coupled changes in PRs"
inputs:
  fail_on_error:
    description: "Whether to fail the job if there are coupled changes"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Changed Files
      id: changed
      uses: tj-actions/changed-files@v36.1.0
      with:
        separator: ","
        # only pick the liquibase master file and production .java files
        files: |
          src/main/resources/db/changelog/master.{yaml,yml,xml}
          src/main/**/*.java
    - name: Checking for bundled Database and Code changes
      # The line breaks don't work with if condition, so have to keep this ugly long condition
      if: ${{contains(steps.changed.outputs.all_changed_files, 'java') && (contains(steps.changed.outputs.all_changed_files, 'yaml') || contains(steps.changed.outputs.all_changed_files, 'yml') || contains(steps.changed.outputs.all_changed_files, 'xml'))}}
      run: |
        SUMMARY=$'## DB changes are coupled with application code changes. Please separate them into different PRs.\n
        Such coupled changes can cause incidents on production and make deployments hard to rollback if needed.'
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.fail_on_error }}" = "true" ]; then
          echo "::error::DB changes are coupled with the application code changes. Please separate them into different PRs."
          exit 1
        fi
      shell: bash