name: PR Quality Check
permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v36.1.0
        with:
          separator: ","
          files: |
            src/main/resources/db/changelog/*.{yaml,xml}
            src/main/**/*.java
            src/test/**/*.java
      - name: Check for bundled Database and Code changes
        if: ${{contains(steps.changed-files.outputs.all_changed_files, 'java') && contains(steps.changed-files.outputs.all_changed_files, 'yaml')}}
        run: |
          echo "** DB changes are bundled with code changes **"
          exit 1