name: PR Quality Check
permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changed Files
        if: ${{ success() }}
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: |
            src/main/resources/db/changelog/master.yaml
            src/main/resources/db/changelog/master.xml
            src/main/**/*.java
            src/test/**/*.java
      - name: Check PR Size
        run: |
          all_files_count=${{ steps.changed-files.outputs.all_changed_files }} | wc -l
#          echo "** PR size is too big ** $all_files_count"
      - name: Check for bundled Database and Code changes
        if: |
          ${{
            contains(join(steps.changed-files.outputs.all_changed_files, ','), 'java') && 
            (contains(join(steps.changed-files.outputs.all_changed_files, ','), 'yaml') || contains(join(steps.changed-files.outputs.all_changed_files, ','), 'xml'))
          }}
        run: |
          echo "** DB changes are bundled with code changes **"          
          exit 1