name: PR Quality Check
permissions:
  contents: read
on:
  pull_request:
    branches: [ master ]

jobs:
  pr-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

coupledchanges:
  name: PR Quality Check
  runs-on: ubuntu-latest
  permissions:
    contents: read
  steps:
    - name: Coupled DB and Code Changes
      uses: lranasingha/auto-gen-microservice/coupledchanges@v1
      with:
        fail_on_error: true