name: Check if DB changes are bundled with Code changes

permissions:
  contents: read

on:
  pull_request:
    branches: [master]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Changed Files
        shell: bash
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
              echo "$file was changed"
          done
