name: Check if DB changes are bundled with Code changes

permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: |
            **/db/changelog/master.yml
            **/src/main/**/*.java
            **/src/test/**/*.java
      - name: List all changed files
        if: steps.changed-files.outputs.only_changed == 'true'
        run: |
          echo "WARNING: DB changes are bundled with Code changes"
          echo "List all the files that have changed: ${{ steps.changed-files.outputs.all_changed_files }}"