name: PR Quality Check
permissions:
  contents: read
on:
  pull_request:
    branches: [master]

jobs:
  coupledchanges:
    name: PR Quality Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Coupled DB and Code Changes
        uses: .github/coupledchanges
        with:
          fail_on_error: true