name: PR Quality Check
permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changed Files
        id: changed
        uses: tj-actions/changed-files@v36.1.0
        with:
          separator: ","
          files: |
            src/main/resources/db/changelog/master.{yaml,yml,xml}
            src/main/**/*.java
            src/test/**/*.java
      - name: Check for bundled Database and Code changes
        #This is long and ugly, but multiline conditions don't seem to work
        if: ${{contains(steps.changed.outputs.all_changed_files, 'java') && (contains(steps.changed.outputs.all_changed_files, 'yaml') || contains(steps.changed.outputs.all_changed_files, 'xml'))}}
        run: echo "::erorr::DB changes are bundled with code changes. Please separate them into different PRs."