name: PR Quality Check
permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  pr-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changed Files
        if: ${{ success() }}
        id: changed-files
        uses: tj-actions/changed-files@v36.1.0
        with:
          separator: ","
          files: |
            src/main/resources/db/changelog/*.{yaml,xml}
            src/main/**/*.java
            src/test/**/*.java
      - name: Check for bundled Database and Code changes
        env:
          ALL_FILES: {{$ steps.changed-files.outputs.all_changed_files }}
#        if: |
#          ${{
#            contains(join(steps.changed-files.outputs.all_changed_files, ','), 'java') &&
#            (contains(join(steps.changed-files.outputs.all_changed_files, ','), 'yaml') || contains(join(steps.changed-files.outputs.all_changed_files, ','), 'xml'))
#          }}
        run: |
          echo "The job_id is: $ALL_FILES" 
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          echo "** DB changes are bundled with code changes **"
          exit 1