name: Check if DB changes are bundled with Code changes

permissions:
  contents: read

on:
  pull_request:
    branches: [ master ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Changed DB and Code files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          files: |
            **/db/changelog/master.yml
            **/src/main/**/*.java
            **/src/test/**/*.java
      - name: Check if DB changes are bundled with Code changes
        if: ${{steps.changed-files.outputs.all_changed_files}}
        run: |
          echo "** DB changes are bundled with code changes **"
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          exit 1